USE TimesheetDatabase
DELETE FROM Entry
DELETE FROM EntryRAM
DELETE FROM Timesheet
--DELETE FROM TimesheetRAM
DELETE FROM Staff
DBCC CHECKIDENT('Entry', RESEED, 0)
DBCC CHECKIDENT('EntryRAM', RESEED, -1)
DBCC CHECKIDENT('Timesheet', RESEED, 0)
--DBCC CHECKIDENT('TimesheetRAM', RESEED, -1)